name: Linux

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cubit: [17_1_0, 2020_0]
        os: [ubuntu-18.04, ubuntu-20.04]

        include:
          - cubit: 17.1.0
            os: ubuntu-18.04
            URL: LINUX_CUBIT_17_1_0
            URL_SDK: LINUX_CUBIT_SDK_17_1_0
            
          - cubit: 2020.0
            os: ubuntu-20.04
            URL: ${{ secrets.LINUX_CUBIT_2020_2 }}
            URL_SDK: ${{ secrets.LINUX_CUBIT_SDK_2020_2 }}

    name: 'Cubit Svalinn Plugin ${{ matrix.cubit }} Build'


    steps:
      - uses: actions/checkout@v2

      - name: Environment Variables
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          if [ "${{ matrix.cubit }}" = "17_1_0" ]; then
            echo "CUBIT_PATH=\"/opt/Trelis-17.1\"" >> $GITHUB_ENV
            echo "CMAKE_ADDITIONAL_FLAG=\"-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0\"" >> $GITHUB_ENV
          else
            echo "CUBIT_PATH=\"/opt/Coreform-Cubit-2020.2\"" >> $GITHUB_ENV
            echo "CMAKE_ADDITIONAL_FLAG=\"\"" >> $GITHUB_ENV
          fi



      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y g++ libeigen3-dev libhdf5-dev patchelf git cmake
       
      - name: Build MOAB
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv moab/bld
          cd moab
          git clone https://bitbucket.org/fathomteam/moab -b Version5.1.0
          cd bld
          cmake ../moab \
                -DENABLE_HDF5=ON \
                -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial \
                -DBUILD_SHARED_LIBS=ON \
                -DENABLE_BLASLAPACK=OFF \
                -DENABLE_FORTRAN=OFF \
                $CMAKE_ADDITIONAL_FLAG \
                -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/moab

          make -j`grep -c processor /proc/cpuinfo`
          make install
          cd ../..
          rm -rf moab/moab moab/bld

      - name: build DAGMC
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv DAGMC/bld
          cd DAGMC
          git clone https://github.com/bam241/DAGMC -b build_exe
          cd bld
          cmake ../DAGMC \
                -DMOAB_DIR=${PLUGIN_ABS_PATH}/moab \
                -DBUILD_UWUW=ON \
                -DBUILD_TALLY=OFF \
                -DBUILD_BUILD_OBB=OFF \
                -DBUILD_MAKE_WATERTIGHT=ON \
                -DBUILD_SHARED_LIBS=ON \
                -DBUILD_STATIC_LIBS=OFF \
                -DBUILD_EXE=OFF \
                -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                -DCMAKE_BUILD_TYPE=Release \
                $CMAKE_ADDITIONAL_FLAG \
                -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/DAGMC
          make -j`grep -c processor /proc/cpuinfo`
          make install
          cd ../..
          rm -rf DAGMC/DAGMC DAGCM/bld

      - name: Trelis setup
        shell: bash
        env:   
          CUBIT_DEB_URL: ${{ secrets[matrix.URL] }}
          CUBIT_SDK_URL: ${{ secrets[matrix.URL_SDK] }}
        run: |
          if [ "${{ matrix.cubit }}" = "2020_2" ]; then
            sudo apt-get -y install libglew2.1 libglu1-mesa libopengl0 ocl-icd-libopencl1 libcxsparse3 libopenblas0 libegl1
          fi

          cd ${PLUGIN_ABS_PATH}
          curl -L https://uwmadison.box.com/shared/static/${CUBIT_DEB_URL}.deb --output trelis.deb
          sudo dpkg -i trelis.deb


          cd /opt
          curl -L https://uwmadison.box.com/shared/static/${CUBIT_SDK_URL}.gz --output trelis_sdk.tar.gz
          sudo tar -zxvf trelis_sdk.tar.gz
 
          if [ "${{ matrix.cubit }}" = "2020_2" ]; then
            cd ${CUBIT_PATH}/bin
            sudo cp -pv CubitExport.cmake CubitExport.cmake.orig
            sudo sed -i "s/\"\/\.\.\/app_logger\"/\"\"/" CubitExport.cmake
            sudo cp -pv CubitUtilConfig.cmake CubitUtilConfig.cmake.orig
            sudo sed -i "s/\/\.\.\/app_logger\;//" CubitUtilConfig.cmake
          fi


      - name: build plugin
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          cd Trelis-plugin
          git submodule update --init
          cd ../
          mkdir -pv bld
          cd bld
          cmake ../Trelis-plugin \
                -DCUBIT_ROOT=${CUBIT_PATH} \
                -DDAGMC_DIR=${PLUGIN_ABS_PATH}/DAGMC \
                -DCMAKE_BUILD_TYPE=Release \
                $CMAKE_ADDITIONAL_FLAG \
                -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}
          make -j`grep -c processor /proc/cpuinfo`
          make install

      - name: prepare pkg
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -p pack/bin/plugins/svalinn
          cd pack/bin/plugins/svalinn

          # Copy all needed libraries into current directory
          cp -pPv ${PLUGIN_ABS_PATH}/lib/* .
          cp -pPv ${PLUGIN_ABS_PATH}/moab/lib/libMOAB.so* .
          cp -pPv ${PLUGIN_ABS_PATH}/DAGMC/lib/libdagmc.so* .
          cp -pPv ${PLUGIN_ABS_PATH}/DAGMC/lib/libmakeWatertight.so* .
          cp -pPv ${PLUGIN_ABS_PATH}/DAGMC/lib/libpyne_dagmc.so* .
          cp -pPv ${PLUGIN_ABS_PATH}/DAGMC/lib/libuwuw.so* .
          cp -pPv /usr/lib/x86_64-linux-gnu/libhdf5_serial.so* .
          chmod 644 *

          # Set the RPATH to be the current directory for the DAGMC libraries
          patchelf --set-rpath ${CUBIT_PATH}/bin/plugins/svalinn libMOAB.so
          patchelf --set-rpath ${CUBIT_PATH}/bin/plugins/svalinn libdagmc.so
          patchelf --set-rpath ${CUBIT_PATH}/bin/plugins/svalinn libmakeWatertight.so
          patchelf --set-rpath ${CUBIT_PATH}/bin/plugins/svalinn libpyne_dagmc.so
          patchelf --set-rpath ${CUBIT_PATH}/bin/plugins/svalinn libuwuw.so

          # Create the Svalinn plugin tarball
          cd ..
          ln -sv svalinn/libsvalinn_plugin.so .
          cd ../..
          tar --sort=name -czvf svalinn-plugin_linux_cubit_${{ matrix.cubit }}.tgz bin


      - name: 'Upload package'
        uses: actions/upload-artifact@v2
        with:
          name: svalinn-plugin_linux
          path: /home/runner/work/Trelis-plugin/pack/svalinn-plugin_linux_${{ matrix.cubit }}.tgz

