name: MACOS

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - cubit: 17.1.0
            os: macos-10.15
            URL: MAC_CUBIT_17_1_0.dmg
            URL_SDK: MAC_CUBIT_SDK_17_1_0.gz
            CUBIT_BASE_NAME: Trelis-17.1
            
          - cubit: 2020.2
            os: macos-10.15
            URL: MAC_CUBIT_2020_2.pkg
            URL_SDK: MAC_CUBIT_SDK_2020_2.gz
            CUBIT_BASE_NAME: Coreform-Cubit-2020.2

    name: 'Trelis/Cubit Svalinn Plugin ${{ matrix.cubit }} Build for Macos'

    steps:
      - uses: actions/checkout@v2

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "FOLDER_PKG=$GITHUB_WORKSPACE/../pkg" >> $GITHUB_ENV
          echo "CUBIT_PATH=/Applications/${{ matrix.CUBIT_BASE_NAME }}.app/Contents" >> $GITHUB_ENV
          if [ "${{ matrix.cubit }}" = "17.1.0" ]; then
            echo "CMAKE_ADDITIONAL_FLAGS=-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0" >> $GITHUB_ENV
            echo "TRELIS_PKG=Trelis-17.1.0-Mac64.dmg" >> $GITHUB_ENV
            echo "TRELIS_SDK_PKG=Trelis-SDK-17.1.0-Mac64.tar.gz" >> $GITHUB_ENV
          else
            echo "TRELIS_PKG=Coreform-Cubit-2020.2-Mac64.pkg" >> $GITHUB_ENV
            echo "TRELIS_SDK_PKG=TCoreform-Cubit-2020.2-Mac64-SDK.tar.gz" >> $GITHUB_ENV
          fi
          echo "BUILD_SHARED_LIBS=OFF" >> $GITHUB_ENV
          echo "BUILD_STATIC_LIBS=ON" >> $GITHUB_ENV
          echo "" >> ${HOME}/.bash_profile
          echo "source $GITHUB_WORKSPACE/scripts/unix_share_build.sh" >> $HOME/.bash_profile


      - name: Initial setup
        shell: bash -l {0}
        run: |
          tail $HOME/.bash_profile
          ls -l $GITHUB_WORKSPACE/scripts
          mac_install_prerequisites



      - name: Downloading packages
        shell: bash -l {0}
        env:   
          CUBIT_PKG_URL: ${{ secrets[matrix.URL] }}
          CUBIT_SDK_URL: ${{ secrets[matrix.URL_SDK] }}
        run: |
          mkdir -p $FOLDER_PKG
          cd ${FOLDER_PKG}
          echo ${TRELIS_PKG}
          curl -L https://uwmadison.box.com/shared/static/${CUBIT_PKG_URL} --output ${TRELIS_PKG}
          curl -L https://uwmadison.box.com/shared/static/${CUBIT_SDK_URL} --output ${TRELIS_SDK_PKG}
          


      - name: Build MOAB
        shell: bash -l {0}
        run: |
          build_moab

      - name: Build DAGMC
        shell: bash -l {0}
        run: |
          build_dagmc

      - name: Trelis setup
        shell: bash -l {0}
        run: |
          mac_setup_cubit_sdk ${{ matrix.cubit }}

      - name: Build plugin
        shell: bash -l {0}
        run: |
          build_plugin 
          
      - name: Prepare package
        shell: bash -l {0}
        run: |
          mac_build_plugin_pkg ${{ matrix.cubit }}


      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: svalinn-plugin_mac_${{ matrix.cubit }}
          path: /Users/runner/work/Trelis-plugin/pack/svalinn-plugin_mac_cubit_${{ matrix.cubit }}.tgz

