name: MACOS

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: macos-10.15
    strategy:
      matrix:
        include:
          - cubit: 17.1.0
            URL: MAC_CUBIT_17_1_0
            URL_SDK: MAC_CUBIT_SDK_17_1_0
            CUBIT_BASE_NAME: Trelis-17.1
            
          - cubit: 2020.2
            URL: MAC_CUBIT_2020_2
            URL_SDK: MAC_CUBIT_SDK_2020_2
            CUBIT_BASE_NAME: Coreform-Cubit-2020.2

    name: 'Trelis/Cubit Svalinn Plugin ${{ matrix.cubit }} Build for Macos'

    steps:
      - uses: actions/checkout@v2

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "FOLDER_PKG=$GITHUB_WORKSPACE/../pkg" >> $GITHUB_ENV
          echo "CUBIT_PATH=/Applications/${{ matrix.CUBIT_BASE_NAME }}.app/Contents" >> $GITHUB_ENV
          if [ "${{ matrix.cubit }}" = "17.1.0" ]; then
            echo "CMAKE_ADDITIONAL_FLAG=-DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0" >> $GITHUB_ENV
            echo "TRELIS_PKG=Trelis-17.1.0-Mac64.dmg" >> $GITHUB_ENV
            echo "TRELIS_SDK_PKG=Trelis-SDK-17.1.0-Mac64.tar.gz" >> $GITHUB_ENV
          else
            echo "TRELIS_PKG=Coreform-Cubit-2020.2-Mac64.pkg" >> $GITHUB_ENV
            echo "TRELIS_SDK_PKG=TCoreform-Cubit-2020.2-Mac64-SDK.tar.gz" >> $GITHUB_ENV
          fi
          echo "BUILD_SHARED_LIBS="ON" >> $GITHUB_ENV
          echo "BUILD_STATIC_LIBS="OFF" >> $GITHUB_ENV
          echo "source $GITHUB_WORKSPACE/scripts/unix_share_build.sh" >> $HOME/.profile


      - name: Initial setup
        shell: bash -l {0}
        run: |
          source $HOME/.profile
          mac_install_prerequisites



      - name: Downloading packages
        shell: bash -l {0}
        env:   
          CUBIT_DEB_URL: ${{ secrets[matrix.URL] }}
          CUBIT_SDK_URL: ${{ secrets[matrix.URL_SDK] }}
        run: |
          source $HOME/.profile
          mkdir -p $FOLDER_PKG
          cd ${FOLDER_PKG}
          if [ "${{ matrix.cubit }}" = "17.1.0" ]; then
            curl -L https://uwmadison.box.com/shared/static/${CUBIT_DEB_URL}.dmg --output ${TRELIS_PKG}
          elif [ "${{ matrix.cubit }}" = "2020.2" ]; then
            curl -L https://uwmadison.box.com/shared/static/${CUBIT_DEB_URL}.pkg --output ${TRELIS_PKG}
          fi
          sudo curl -L https://uwmadison.box.com/shared/static/${CUBIT_SDK_URL}.gz --output ${TRELIS_SDK_PKG}
          


      - name: Build MOAB
        shell: bash -l {0}
        run: |
          source $HOME/.profile
          build_moab

      - name: Build DAGMC
        shell: bash -l {0}
        run: |
          source $HOME/.profile
          build_dagmc

      - name: Trelis steup
        shell: bash -l {0}
        run: |
          source $HOME/.profile
          mac_setup_trelis_sdk ${{ matrix.cubit }}

      - name: Build plugin
        shell: bash -l {0}
        run: |
          source $HOME/.profile
          build_plugin 
          
      - name: Prepare package
        shell: bash -l {0}
        run: |
          source $HOME/.profile
          mac_build_plugin_pkg ${{ matrix.cubit }}


      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: svalinn-plugin_mac_${{ matrix.cubit }}
          path: /Users/runner/work/Trelis-plugin/pack/svalinn-plugin_mac_cubit_${{ matrix.cubit }}.tgz

