name: MACOS

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: macos-10.15
    strategy:
      matrix:
        include:
          - cubit: 17_1_0
            URL: MAC_CUBIT_17_1_0
            URL_SDK: MAC_CUBIT_SDK_17_1_0
            CUBIT_BASE_NAME: Trelis-17.1
            
          - cubit: 2020_2
            URL: MAC_CUBIT_2020_2
            URL_SDK: MAC_CUBIT_SDK_2020_2
            CUBIT_BASE_NAME: Coreform-Cubit-2020.2

    name: 'Trelis/Cubit Svalinn Plugin ${{ matrix.cubit }} Build for Macos'

    steps:
      - uses: actions/checkout@v2

      - name: Environment Variables
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "TRELIS_INSTALL_LOC=/Applications/${{ matrix.CUBIT_BASE_NAME }}.app/Contents" >> $GITHUB_ENV

      - name: Brew dependencies
        shell: bash
        run: |
          brew install eigen hdf5 gcc@6 

      - name: Trelis setup
        shell: bash
        env:   
          CUBIT_DEB_URL: ${{ secrets[matrix.URL] }}
          CUBIT_SDK_URL: ${{ secrets[matrix.URL_SDK] }}
        run: |
          cd ${PLUGIN_ABS_PATH}
          if [ "${{ matrix.cubit }}" = "17_1_0" ]; then
            curl -L https://uwmadison.box.com/shared/static/${CUBIT_DEB_URL}.dmg --output trelis.dmg
            hdiutil convert trelis.dmg -format UDTO -o trelis_eula.dmg
            hdiutil attach trelis_eula.dmg.cdr
            mv /Volumes/Trelis-17.1.0-Mac64/*.app /Applications/
            hdiutil detach /Volumes/Trelis-17.1.0-Mac64
            rm -rf trelis.dmg
            
          elif [ "${{ matrix.cubit }}" = "2020_2" ]; then
            curl -L https://uwmadison.box.com/shared/static/${CUBIT_DEB_URL}.pkg --output cubit.pkg
            sudo installer -pkg cubit.pkg -target /
            rm -rf cubit.pkg

          fi
          cd $TRELIS_INSTALL_LOC
          sudo curl -L https://uwmadison.box.com/shared/static/${CUBIT_SDK_URL}.gz --output trelis_sdk.tar.gz
          tar -xzf trelis_sdk.tar.gz
          mv ${{ matrix.CUBIT_BASE_NAME }}/* ./
          mv ${{ matrix.CUBIT_BASE_NAME }}.app/Contents/MacOS/* MacOS/
          mv bin/* MacOS/
          rm -rf bin ${{ matrix.CUBIT_BASE_NAME }}.app
          ln -s MacOS bin
          ln -s ${TRELIS_INSTALL_LOC}/include /Applications/include
   
      - name: Build MOAB
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv moab/bld
          cd moab
          git clone https://bitbucket.org/fathomteam/moab -b Version5.1.0
          cd bld
          cmake ../moab -DENABLE_HDF5=ON \
                    -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial \
                    -DBUILD_SHARED_LIBS=OFF \
                    -DENABLE_BLASLAPACK=OFF -DENABLE_FORTRAN=OFF \
                    -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 \
                    -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/moab
          make -j
          make install
          cd ../..
          rm -rf moab/moab moab/bld

      - name: Build DAGMC
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv DAGMC/bld
          cd DAGMC
          git clone https://github.com/bam241/DAGMC -b build_exe
          cd bld
          cmake ../DAGMC -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 \
                        -DMOAB_DIR=${PLUGIN_ABS_PATH}/moab \
                        -DBUILD_UWUW=ON \
                        -DBUILD_TALLY=OFF \
                        -DBUILD_BUILD_OBB=OFF \
                        -DBUILD_MAKE_WATERTIGHT=ON \
                        -DBUILD_SHARED_LIBS=OFF \
                        -DBUILD_STATIC_LIBS=ON \
                        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/DAGMC
          make -j
          make install
          cd ../..
          rm -rf DAGMC/DAGMC DAGCM/bld

       
      - name: Build plugin
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}/Trelis-plugin
          git submodule update --init

          cd ${PLUGIN_ABS_PATH}/Trelis-plugin
          cp scripts/*.cmake ${TRELIS_INSTALL_LOC}/MacOS/

          rm -rf bld
          mkdir -pv bld
          cd bld
          cmake .. -DCubit_DIR=${TRELIS_INSTALL_LOC}/MacOS \
                  -DCUBIT_ROOT=${TRELIS_INSTALL_LOC}/MacOS \
                  -DDAGMC_DIR=${PLUGIN_ABS_PATH}/DAGMC \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}
          make -j
          make install

      - name: Prepare package
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -p pack/MacOS/plugins/svalinn
          cd pack/MacOS/plugins/svalinn

          # Copy all needed libraries into current directory
          cp -pPv ${PLUGIN_ABS_PATH}/lib/* .

          # Create the Svalinn plugin tarball
          cd ..
          ln -sv svalinn/libsvalinn_plugin.so .
          cd ../..
          tar -czvf svalinn-plugin_mac_17.1.tgz MacOS

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: svalinn-plugin_mac
          path: /Users/runner/work/Trelis-plugin/pack/svalinn-plugin_mac_17.1.tgz

